extends Node3D
## The walkable town round the Rynek, laid out from data/city_layout.json (generated by tools/gen_city_layout.py;
## assets from the BUILDINGS PASS 2/3 sections of assets/blender/build_assets.py). Instanced by greybox_district.gd
## after the square is built.
##
## Layout (Godot metres, +X east, +Z south; the Rynek is +-45 round the origin and belongs to greybox_district.gd):
##   The city wall ring (x=+-100, z=-100 north, z=96 south) with towers every ~32 m and a frozen moat outside;
##   St Florian's Gate (x=10) with the Barbican beyond it to the north, the Slawkowska gate (x=-68) north, the
##   Garbary gate west (z=0), the Mikolajska gate east (z=-10) and the Grodzka gate south (x=-12).
##   Inside: a street grid that keeps the carriage lanes of data/npcs.json (x=-42.5, z=40.5, x=40, the NW corner and
##   the east gap) and adds Szewska/Jagiellonska/Florianska/Grodzka/Mikolajska and cross streets, blocks of
##   tenements (the five square modules and the nine new ones) with courtyard walls, the Maly Rynek east of
##   St Mary's with its stalls, the Collegium Maius, the campanile, a monastery enclosure south of the square.
##   Outside: Kleparz market north past the Barbican (brewery, windmill), Garbary west (tanners, the water mill on
##   the Mlynowka, the forge, the bell foundry, the cooper), the Vistula quays south-west (granaries, wharves, salt
##   barges frozen in, the fish market), the near castle gate under Wawel (Wawel itself on the skyline), Kazimierz
##   south over the frozen Old Vistula (houses, the Old Synagogue, the wooden synagogue, the Uniate church), and
##   farmland east (fields, a farmstead, the manor, a shrine and the gallows by the road).
## Streets carry collision with a `surface` meta (cobbles, mud, gravel; snow elsewhere) for the stealth footsteps,
## cobble slabs or trodden slush on top, and continuous gutters (rynsztok) generated from the same street lines:
## straight channel pieces, mitred corners, crossing slabs at junctions and doorways, drains at the ends.
## The outer navmesh is baked in chunks that butt onto the square's region (see _bake_nav), so the whole town is
## walkable for the townsfolk; the smoke prints which district targets are reachable from the square.
## `-- --outer-shot=/dir` (needs a window) saves an overhead of the whole city, each district's main street and
## close-ups of the new buildings.

const FlickerLight := preload("res://scripts/city/flicker.gd")
const LAYOUT := "res://data/city_layout.json"
const VIS := {"prop": 120.0, "house": 320.0, "big": 0.0, "far": 0.0}
const NAV_X := [-235.0, -160.0, -105.0, -45.0, 45.0, 105.0, 160.0, 235.0]
const NAV_Z := [-205.0, -150.0, -105.0, -45.0, 45.0, 105.0, 160.0, 215.0]

static var _shot_done := false
var data: Dictionary = {}
var _loading: Dictionary = {}          ## glb path -> true while its threaded load is pending
var _loaded: Array = []                ## keeps the loaded PackedScenes referenced
var _t0 := 0
var _tb := 0
var built := false                     ## true once every building is placed (then the navmesh chunks bake)


func _process(_delta: float) -> void:
	if built:
		set_process(false)
		return
	for path in _loading.keys():
		var st := ResourceLoader.load_threaded_get_status(path)
		if st == ResourceLoader.THREAD_LOAD_IN_PROGRESS:
			return
	for path in _loading.keys():
		if ResourceLoader.load_threaded_get_status(path) == ResourceLoader.THREAD_LOAD_LOADED:
			_loaded.append(ResourceLoader.load_threaded_get(path))
	_loading.clear()
	var t1 := Time.get_ticks_msec()
	_place_all()
	built = true
	print("[smoke] city built: load %d ms, place %d ms" % [t1 - _t0, Time.get_ticks_msec() - t1])
	_fires()
	_street_lights()
	_climbables()
	_bake_nav()
var _mesh_cache: Dictionary = {}
var _nav_pending := 0
var _nav_regions: Array = []


func _ready() -> void:
	name = "OuterCity"
	if "--no-outer" in OS.get_cmdline_user_args():
		return
	var f := FileAccess.open(LAYOUT, FileAccess.READ)
	if f:
		var d: Variant = JSON.parse_string(f.get_as_text())
		if d is Dictionary:
			data = d
	if data.is_empty():
		push_warning("OuterCity: cannot read %s" % LAYOUT)
	_t0 = Time.get_ticks_msec()
	_ground()
	_streets()
	_gutters()
	_drifts()
	# the buildings load on worker threads (each glb carries its own textures, so the first load is slow) and
	# are placed when all have arrived; the square plays meanwhile
	for e in data.get("place", []):
		var path := "res://assets/models/%s.glb" % str(e["a"])
		if not _loading.has(path) and ResourceLoader.exists(path):
			_loading[path] = true
			ResourceLoader.load_threaded_request(path, "", true)
	set_process(true)
	var dir := _shot_dir()
	if dir != "" and not _shot_done:
		_shot_done = true
		_shots.call_deferred(dir)


# ------------------------------------------------------------------ ground
func _body(surface: String) -> StaticBody3D:
	var n := "Ground_" + surface
	var b := get_node_or_null(n) as StaticBody3D
	if b == null:
		b = StaticBody3D.new()
		b.name = n
		b.set_meta("surface", surface)
		add_child(b)
	return b


func _box(surface: String, x0: float, z0: float, x1: float, z1: float, top: float = 0.0) -> void:
	var cs := CollisionShape3D.new()
	var bs := BoxShape3D.new()
	bs.size = Vector3(absf(x1 - x0), 1.0, absf(z1 - z0))
	cs.shape = bs
	cs.position = Vector3((x0 + x1) * 0.5, top - 0.5, (z0 + z1) * 0.5)
	_body(surface).add_child(cs)


func _mat(look: String) -> StandardMaterial3D:
	var key := "mat_" + look
	if _mesh_cache.has(key):
		return _mesh_cache[key]
	var m := StandardMaterial3D.new()
	match look:
		"snow":
			m.albedo_color = Color(0.82, 0.85, 0.92)
			m.roughness = 0.85
			_tex(m, "snow", 0.5)
		"ice":
			m.albedo_color = Color(0.55, 0.66, 0.76)
			m.roughness = 0.12
			m.metallic_specular = 0.8
			_tex(m, "snow", 0.08)
		"mud", "gravel":
			m.albedo_color = Color(0.72, 0.70, 0.68) if look == "mud" else Color(0.80, 0.78, 0.74)
			m.roughness = 0.9
			_tex(m, "slush", 0.5)
	_mesh_cache[key] = m
	return m


func _tex(m: StandardMaterial3D, kind: String, uv: float) -> void:
	var col := "res://assets/textures/%s_col.png" % kind
	if ResourceLoader.exists(col):
		m.albedo_texture = load(col)
		m.uv1_triplanar = true
		m.uv1_world_triplanar = true
		m.uv1_scale = Vector3(uv, uv, uv)
		var nrm := "res://assets/textures/%s_nrm.png" % kind
		if ResourceLoader.exists(nrm):
			m.normal_enabled = true
			m.normal_texture = load(nrm)


func _plane(look: String, x0: float, z0: float, x1: float, z1: float, y: float) -> void:
	var mi := MeshInstance3D.new()
	var pm := PlaneMesh.new()
	pm.size = Vector2(absf(x1 - x0), absf(z1 - z0))
	pm.material = _mat(look)
	mi.mesh = pm
	mi.position = Vector3((x0 + x1) * 0.5, y, (z0 + z1) * 0.5)
	mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	add_child(mi)


## Snow everywhere outside the cobbled square, then the layout's patches (squares, yards, quays, flagstone strips;
## moat and river ice) and the streets, each paved with 4 m ground slabs on the square's grid (one MultiMesh per
## surface kind and street) over collision boxes carrying the footstep `surface` meta.
const SURF := {"cobbles": ["ground_cobbles_lo", "cobbles", "cobbles"], "rough": ["ground_cobbles_rough", "cobbles", "cobbles"],
		"dirt": ["ground_mud", "mud", "mud"], "mud": ["ground_mud", "mud", "mud"], "gravel": ["ground_gravel", "gravel", "mud"],
		"flags": ["ground_flags", "cobbles", "flags"]}
var _cells: Dictionary = {}           ## Vector2i -> true: a 4 m cell already paved
var _surface_report: Dictionary = {}  ## surface kind -> [street names]


func _ground() -> void:
	_box("snow", -400, -400, 400, 400, -0.02)
	_plane("snow", -400, -400, 400, 400, -0.02)
	var patches: Array = data.get("ground", [])
	patches.sort_custom(func(p: Dictionary, q: Dictionary) -> bool: return str(p.get("look", "")) == "flags" and str(q.get("look", "")) != "flags")
	for g in patches:
		var r: Array = g["rect"]
		var look := str(g.get("look", "snow"))
		if look == "ice":
			_plane("ice", r[0], r[1], r[2], r[3], -0.012)
			continue
		var kind := look if SURF.has(look) else "mud"
		_box(str(g.get("surface", SURF[kind][1])), r[0], r[1], r[2], r[3], 0.012 if kind == "flags" else 0.0)
		_pave(kind, r[0], r[1], r[2], r[3], "patch_%s" % kind, kind == "flags")


func _street_rect(s: Dictionary, a: Array, b: Array) -> Rect2:
	var w: float = float(s.get("w", 8.0))
	var x0 := minf(a[0], b[0]) - w * 0.5
	var x1 := maxf(a[0], b[0]) + w * 0.5
	var z0 := minf(a[1], b[1]) - w * 0.5
	var z1 := maxf(a[1], b[1]) + w * 0.5
	return Rect2(x0, z0, x1 - x0, z1 - z0)


func _streets() -> void:
	var order := ["cobbles", "rough", "gravel", "dirt", "mud"]
	var planks: Array[Transform3D] = []
	for kind in order:
		for s in data.get("streets", []):
			if str(s.get("surface", "cobbles")) != kind:
				continue
			var pts: Array = s["pts"]
			if not _surface_report.has(kind):
				_surface_report[kind] = []
			(_surface_report[kind] as Array).append(str(s["name"]))
			for i in pts.size() - 1:
				var r := _street_rect(s, pts[i], pts[i + 1])
				_box(SURF[kind][1], r.position.x, r.position.y, r.end.x, r.end.y, 0.0)
				_pave(kind, r.position.x, r.position.y, r.end.x, r.end.y, str(s["name"]), false)
				if kind == "dirt":
					# a plank walkway along the right-hand side where the mud is deepest
					var a := Vector3(float(pts[i][0]), 0, float(pts[i][1]))
					var b := Vector3(float(pts[i + 1][0]), 0, float(pts[i + 1][1]))
					var L := a.distance_to(b)
					var d := (b - a) / maxf(0.01, L)
					var side := Vector3(-d.z, 0, d.x) * (float(s.get("w", 8.0)) * 0.5 - 0.7)
					var rot := atan2(-d.z, d.x)
					for k in int(L / 4.0):
						var c := a + d * (2.0 + 4.0 * k) + side
						planks.append(Transform3D(Basis(Vector3.UP, rot), c))
						var bx := CollisionShape3D.new()
						var bs := BoxShape3D.new()
						bs.size = Vector3(4.0, 0.12, 1.2)
						bx.shape = bs
						bx.transform = Transform3D(Basis(Vector3.UP, rot), c + Vector3(0, 0.05, 0))
						_body("planks").add_child(bx)
	var pm := _asset_mesh("ground_planks")
	if pm:
		_chunked_multimesh(pm, planks, "Planks")


## Lay 4 m slabs of `kind` over the cells of a rect not already paved (the square's own cells are skipped for
## cobbles; flagstone strips inside the square sit 1.2 cm above its setts).
func _pave(kind: String, x0: float, z0: float, x1: float, z1: float, group: String, raised: bool) -> void:
	var mesh := _slab_mesh(kind)
	if mesh == null:
		return
	var xforms: Array[Transform3D] = []
	for ix in range(int(floor(x0 / 4.0 + 0.5)), int(floor(x1 / 4.0 + 0.5)) + 1):
		for iz in range(int(floor(z0 / 4.0 + 0.5)), int(floor(z1 / 4.0 + 0.5)) + 1):
			var cx := ix * 4.0
			var cz := iz * 4.0
			var key := Vector2i(ix, iz)
			if not raised and absf(cx) <= 44.0 and absf(cz) <= 44.0:
				continue                      # the square's own slabs
			if _cells.has(key):
				continue
			_cells[key] = kind
			xforms.append(Transform3D(Basis.IDENTITY, Vector3(cx, 0.012 if raised else 0.0, cz)))
	_multimesh(mesh, xforms, "Pave_%s_%s" % [kind, group.validate_node_name()], 260.0, false)


## The slab mesh of a surface kind, with the baked height map as parallax like the square's setts.
func _slab_mesh(kind: String) -> Mesh:
	var key := "slab_" + kind
	if _mesh_cache.has(key):
		return _mesh_cache[key]
	var mesh := _asset_mesh(str(SURF[kind][0]))
	var hpath := "res://assets/ground/%s_height.png" % str(SURF[kind][2])
	if mesh and ResourceLoader.exists(hpath) and mesh.get_surface_count() > 0:
		var base := mesh.surface_get_material(0)
		if base is BaseMaterial3D:
			var pm := (base as BaseMaterial3D).duplicate() as BaseMaterial3D
			pm.heightmap_enabled = true
			pm.heightmap_texture = load(hpath)
			pm.heightmap_scale = 2.0
			pm.heightmap_deep_parallax = true
			pm.heightmap_min_layers = 8
			pm.heightmap_max_layers = 24
			mesh = mesh.duplicate()
			mesh.surface_set_material(0, pm)
	_mesh_cache[key] = mesh
	return mesh


func _multimesh(mesh: Mesh, xforms: Array[Transform3D], nm: String, vis: float, shadows: bool) -> void:
	if xforms.is_empty():
		return
	var mm := MultiMesh.new()
	mm.transform_format = MultiMesh.TRANSFORM_3D
	mm.mesh = mesh
	mm.instance_count = xforms.size()
	for i in xforms.size():
		mm.set_instance_transform(i, xforms[i])
	var mmi := MultiMeshInstance3D.new()
	mmi.name = nm
	mmi.multimesh = mm
	mmi.visibility_range_end = vis
	if not shadows:
		mmi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	add_child(mmi)


## The visual mesh of an asset (its first MeshInstance3D outside the collision body), cached.
func _asset_mesh(asset: String) -> Mesh:
	if _mesh_cache.has(asset):
		return _mesh_cache[asset]
	var inst := Assets.instance(asset)
	var mesh: Mesh = null
	if inst:
		var stack: Array = [inst]
		while stack.size() > 0 and mesh == null:
			var n: Node = stack.pop_back()
			if n is MeshInstance3D and not (n.get_parent() is StaticBody3D):
				mesh = (n as MeshInstance3D).mesh
			for c in n.get_children():
				stack.append(c)
		inst.free()
	_mesh_cache[asset] = mesh
	return mesh


# ------------------------------------------------------------------ buildings and props
func _place_all() -> void:
	for e in data.get("place", []):
		var p: Array = e["p"]
		var n := Assets.place(self, str(e["a"]), Vector3(float(p[0]), 0.0, float(p[1])), float(e.get("r", 0.0)), float(e.get("s", 1.0)))
		if n == null:
			continue
		var vis: float = VIS.get(str(e.get("k", "house")), 300.0)
		if vis > 0.0:
			for mi in n.find_children("*", "MeshInstance3D", true, false):
				(mi as MeshInstance3D).visibility_range_end = vis
				(mi as MeshInstance3D).visibility_range_end_margin = 8.0
		if str(e["a"]) == "wawel_far":
			n.name = "WawelFar"
		_tag(n, str(e["a"]))


## Gameplay tags on placed buildings and props: `flammable` (straw, hay, thatch, canvas, timber, laundry),
## `poisonable` (casks and barrels of drink), and the kingpin warehouse's cargo hook rig.
const FLAMMABLE := ["market_stall", "farm_haystack", "farm_haystack_small", "farm_barn", "farm_cottage", "yard_shed",
		"laundry_line", "woodpile_leanto", "straw_scatter", "carpenter_yard", "cooper_yard", "tannery_frame", "klep_stable",
		"broken_stall", "guillotine_parts", "sacks_crates"]
const POISONABLE := ["barrel", "brewery", "cooper_yard", "water_butt", "well", "water_pump"]


func _tag(n: Node, asset: String) -> void:
	if asset in FLAMMABLE:
		n.set_meta("flammable", true)
	if asset in POISONABLE:
		n.set_meta("poisonable", true)
	var hook := n.find_child("CargoHook", true, false)
	if hook:
		hook.set_meta("rig", true)
		hook.set_meta("rig_kind", "drop")
	for nm in ["Bales", "Shavings"]:
		var b := n.find_child(nm, true, false)
		if b:
			b.set_meta("flammable", true)
	for nm in ["Grate", "Lid"]:                  # underground entrances (drain_grate, well_shaft_cap)
		var g := n.find_child(nm, true, false)
		if g:
			g.set_meta("hidden_entrance", true)
			g.add_to_group("hidden_entrance")
	var c := n.find_child("Casks", true, false)
	if c:
		c.set_meta("poisonable", true)


# ------------------------------------------------------------------ gutters from the street lines
## Every street with a gutter gets a continuous channel: along its centre line ("centre") or 0.9 m inside its
## right-hand kerb ("kerb"), in 4 m straight pieces (the last one shortened by overlap), a mitred corner at each
## turn, a crossing slab wherever the channel crosses another street's centre line, and a drain at each open end.
func _gutters() -> void:
	var straight: Array[Transform3D] = []
	var corners: Array[Transform3D] = []
	var slabs: Array[Transform3D] = []
	var drains: Array[Transform3D] = []
	var streets: Array = data.get("streets", [])
	for s in streets:
		var mode := str(s.get("gutter", "none"))
		if mode == "none":
			continue
		var pts: Array = s["pts"]
		var off := 0.0 if mode == "centre" else float(s.get("w", 8.0)) * 0.5 - 0.9
		var line: Array[Vector3] = []
		for i in pts.size():
			var p := Vector3(float(pts[i][0]), 0.0, float(pts[i][1]))
			var dprev := Vector3.ZERO
			var dnext := Vector3.ZERO
			if i > 0:
				dprev = (p - Vector3(float(pts[i - 1][0]), 0.0, float(pts[i - 1][1]))).normalized()
			if i < pts.size() - 1:
				dnext = (Vector3(float(pts[i + 1][0]), 0.0, float(pts[i + 1][1])) - p).normalized()
			var d := (dprev + dnext).normalized()
			var side := Vector3(-d.z, 0, d.x)
			var k := 1.0
			if dprev != Vector3.ZERO and dnext != Vector3.ZERO:
				k = 1.0 / maxf(0.5, side.dot(Vector3(-dnext.z, 0, dnext.x)))
			line.append(p + side * off * k)
		for i in line.size() - 1:
			var a := line[i]
			var b := line[i + 1]
			var seg := b - a
			var L := seg.length()
			if L < 0.5:
				continue
			var dir := seg / L
			var rot := atan2(-dir.z, dir.x)
			var n := int(ceil(L / 4.0))
			var step := (L - 4.0) / maxf(1.0, n - 1) if n > 1 else 0.0
			for k2 in n:
				var c := a + dir * (2.0 + step * k2) if n > 1 else a + dir * (L * 0.5)
				straight.append(Transform3D(Basis(Vector3.UP, rot), c + Vector3(0, 0.002, 0)))
			# crossings: slabs where the channel meets another street's centre line
			for o in streets:
				if o == s:
					continue
				var op: Array = o["pts"]
				for j in op.size() - 1:
					var q0 := Vector3(float(op[j][0]), 0.0, float(op[j][1]))
					var q1 := Vector3(float(op[j + 1][0]), 0.0, float(op[j + 1][1]))
					var hit: Variant = Geometry2D.segment_intersects_segment(Vector2(a.x, a.z), Vector2(b.x, b.z), Vector2(q0.x, q0.z), Vector2(q1.x, q1.z))
					if hit != null:
						var h: Vector2 = hit
						slabs.append(Transform3D(Basis(Vector3.UP, rot + PI * 0.5), Vector3(h.x, 0.004, h.y)))
			# doorway slabs every ~10 m on kerb gutters
			if mode == "kerb":
				var m := int(L / 10.0)
				for k3 in m:
					slabs.append(Transform3D(Basis(Vector3.UP, rot + PI * 0.5), a + dir * (5.0 + 10.0 * k3) + Vector3(0, 0.004, 0)))
		for i in range(1, line.size() - 1):
			var ain := (line[i - 1] - line[i]).normalized()
			var aout := (line[i + 1] - line[i]).normalized()
			var r := atan2(-ain.z, ain.x)
			var ly := Basis(Vector3.UP, r) * Vector3(0, 0, -1)
			if ly.dot(aout) < 0.5:
				r = atan2(-aout.z, aout.x)
			corners.append(Transform3D(Basis(Vector3.UP, r), line[i] + Vector3(0, 0.003, 0)))
		for e in [0, line.size() - 1]:
			var nb := line[1] if e == 0 else line[line.size() - 2]
			var outd := (line[e] - nb).normalized()
			drains.append(Transform3D(Basis(Vector3.UP, atan2(-outd.z, outd.x)), line[e] + Vector3(0, 0.002, 0)))
	for pair in [["gutter_channel", straight], ["gutter_corner", corners], ["gutter_slab", slabs], ["gutter_outfall", drains]]:
		var mesh := _asset_mesh(pair[0])
		if mesh:
			_chunked_multimesh(mesh, pair[1], pair[0])


## MultiMeshes per 64 m cell so distant runs are culled by their visibility range.
func _chunked_multimesh(mesh: Mesh, xforms: Array, nm: String) -> void:
	var cells := {}
	for t in xforms:
		var tr: Transform3D = t
		if nm.begins_with("gutter_"):
			tr.origin.y += 0.012      # clear of the parallax cobble surface: no z-fighting flicker
		var key := Vector2i(int(floor(tr.origin.x / 64.0)), int(floor(tr.origin.z / 64.0)))
		if not cells.has(key):
			cells[key] = [] as Array[Transform3D]
		(cells[key] as Array[Transform3D]).append(tr)
	for key in cells:
		_multimesh(mesh, cells[key], "%s_%d_%d" % [nm, key.x, key.y], 140.0, false)


# ------------------------------------------------------------------ snow drifts against the house fronts
func _drifts() -> void:
	var mesh := _asset_mesh("snow_drift")
	if mesh == null:
		return
	var xforms: Array[Transform3D] = []
	for d in (data.get("points", {}) as Dictionary).get("drifts", []):
		xforms.append(Transform3D(Basis(Vector3.UP, float(d[2])), Vector3(float(d[0]), 0.0, float(d[1]))))
	_chunked_multimesh(mesh, xforms, "Drifts")


# ------------------------------------------------------------------ climbing (read by the player's traversal code)
## Props whose collision body is climbable as a whole, by asset: vault (<= 1.2 m), mantle (<= 2.4 m), ledge.
const CLIMB_PROPS := {"crate_stack": "vault", "barrel": "vault", "cart": "vault", "handcart": "vault", "sledge": "vault",
		"water_trough": "vault", "horse_trough": "vault", "well": "vault", "fountain": "vault", "water_pump": "vault",
		"bench_wood": "vault", "bench_stone": "vault", "park_railing": "vault", "hedge": "vault", "pillory": "vault",
		"stocks": "vault", "sacks_crates": "vault", "market_stall": "mantle", "woodpile_leanto": "mantle", "coach": "mantle",
		"monastery_wall": "ledge", "wawel_wall": "ledge"}


## Every StaticBody3D named climb_<kind>_<n> (exported by build_assets.py: drainpipes, first-floor sills, balconies,
## gallery decks, ladders, shed roofs, low walls, perches, parapets) and the collision of the props above join the
## group "climbable" with meta climb_kind. Runs over the whole district, so the square's tenements count too.
func _climbables() -> void:
	var root := get_parent() if get_parent() else self
	var n_climb := 0
	for n in root.find_children("climb_*", "StaticBody3D", true, false):
		var parts := String(n.name).split("_")
		if parts.size() >= 2:
			n.add_to_group("climbable")
			n.set_meta("climb_kind", parts[1])
			n_climb += 1
	for n in root.find_children("*", "Node3D", true, false):
		var path := String(n.scene_file_path)
		if path == "":
			continue
		var asset := path.get_file().get_basename()
		if CLIMB_PROPS.has(asset):
			for b in n.find_children("*", "StaticBody3D", true, false):
				if not String(b.name).begins_with("climb_"):
					b.add_to_group("climbable")
					b.set_meta("climb_kind", CLIMB_PROPS[asset])
					n_climb += 1
	print("[smoke] city climbable=%d surfaces=%s" % [n_climb, _surface_report])


# ------------------------------------------------------------------ fires
## Warm flickering light at every Furnace_n empty (forge hearth, foundry furnace, brewery kettle fire, the cooper's
## cresset), plus a faint glow behind St Mary's east windows so the stained glass reads at night.
func _fires() -> void:
	for n in find_children("Furnace_*", "", true, false):
		var l := FlickerLight.new()
		l.amount = 0.25
		l.speed = 8.0
		l.light_color = Color(1.0, 0.5, 0.2)
		l.light_energy = 4.0
		l.omni_range = 9.0
		l.omni_attenuation = 1.4
		l.shadow_enabled = false
		l.light_volumetric_fog_energy = 1.2
		(n as Node3D).add_child(l)
		l.position = Vector3(0, 0.4, 0.8)
	for pos in [Vector3(34, 9, -48.5), Vector3(28, 12, -34), Vector3(40, 12, -34)]:
		var g := OmniLight3D.new()
		g.position = pos
		g.light_color = Color(1.0, 0.72, 0.42)
		g.light_energy = 1.2
		g.omni_range = 7.0
		add_child(g)


# ------------------------------------------------------------------ street lighting beyond the square
## Kraków lit its main streets with oil lanterns from the 1770s: posts every ~30 m on the cobbled streets inside
## the walls, sparse ones on the dirt roads outside, and candle-lit windows on a quarter of the outer houses (from
## their Window_n anchors), so the outer town is dim but readable and the stealth light sampling has pools to skirt.
## Lights never cast shadows themselves; the shadow budget grants shadows to the nearest few.
func _street_lights() -> void:
	var rng := RandomNumberGenerator.new()
	rng.seed = 1795
	var posts := 0
	for st in data.get("streets", []):
		var surf := str(st.get("surface", "cobbles"))
		var pts: Array = st["pts"]
		var spacing := 30.0 if surf in ["cobbles", "rough"] else 60.0
		var w := float(st.get("w", 8.0))
		var side := 1.0
		var carry := spacing * 0.5
		for i in pts.size() - 1:
			var a := Vector3(float(pts[i][0]), 0.0, float(pts[i][1]))
			var b := Vector3(float(pts[i + 1][0]), 0.0, float(pts[i + 1][1]))
			var seg := b - a
			var len := seg.length()
			if len < 1.0:
				continue
			var dir := seg / len
			var right := Vector3(dir.z, 0.0, -dir.x)
			var d := carry
			while d < len:
				var p := a + dir * d + right * side * (w * 0.5 - 1.2)
				if absf(p.x) > 46.0 or absf(p.z) > 46.0:      # the square has its own lanterns
					var post := Assets.place(self, "lantern_post", p, atan2(-right.x * side, -right.z * side))
					var l := FlickerLight.new()
					l.amount = 0.10
					l.speed = 7.0
					l.position = p + Vector3(0.9, 2.9, 0).rotated(Vector3.UP, atan2(-right.x * side, -right.z * side))
					l.light_color = Color(1.0, 0.70, 0.40)
					l.light_energy = 7 if surf in ["cobbles", "rough"] else 5
					l.omni_range = 20
					l.omni_attenuation = 1.5
					l.shadow_enabled = false
					l.omni_shadow_mode = OmniLight3D.SHADOW_DUAL_PARABOLOID
					l.light_specular = 0.6
					l.light_volumetric_fog_energy = 1.2
					l.add_to_group("flame_lights")
					l.add_to_group("shadow_capable")
					add_child(l)
					if post:
						post.add_to_group("douseable")
					posts += 1
				side = -side
				d += spacing
			carry = d - len
	var windows := 0
	for n in find_children("Window_*", "", true, false):
		var w3 := n as Node3D
		if w3 == null or rng.randf() > 0.25:
			continue
		var pos := w3.global_position
		if absf(pos.x) < 30.0 and absf(pos.z) < 30.0:
			continue
		var c := FlickerLight.new()
		c.amount = 0.18
		c.speed = 4.0
		c.light_color = Color(1.0, 0.76, 0.42)
		c.light_energy = 2.6
		c.omni_range = 9
		c.omni_attenuation = 1.3
		c.shadow_enabled = false
		c.light_volumetric_fog_energy = 0.6
		c.add_to_group("flame_lights")
		add_child(c)
		c.global_position = pos + w3.global_transform.basis.z * 0.8 + Vector3(0, 0.3, 0)
		windows += 1
	print("[smoke] city lights lanterns=%d candle_windows=%d" % [posts, windows])


# ------------------------------------------------------------------ navigation: chunks round the square
## The square's region (greybox_district.gd) covers +-45 m exactly (baked with a border); the rest of the town is
## baked here in chunks from one parse of the static colliders, each chunk grown by 4 m and trimmed back with
## border_size so neighbouring chunks share their edges and the map joins them.
func _bake_nav() -> void:
	for i in 3:
		await get_tree().physics_frame
	if not is_inside_tree():
		return
	var district := get_parent()
	var proto := NavigationMesh.new()
	proto.geometry_parsed_geometry_type = NavigationMesh.PARSED_GEOMETRY_STATIC_COLLIDERS
	proto.geometry_source_geometry_mode = NavigationMesh.SOURCE_GEOMETRY_GROUPS_WITH_CHILDREN
	proto.geometry_source_group_name = "nav_source"
	var src := NavigationMeshSourceGeometryData3D.new()
	var tp := Time.get_ticks_msec()
	NavigationServer3D.parse_source_geometry_data(proto, src, district)
	_tb = Time.get_ticks_msec()
	print("[smoke] city nav parse %d ms, %d source vertices" % [_tb - tp, src.get_vertices().size() / 3])
	for ix in NAV_X.size() - 1:
		for iz in NAV_Z.size() - 1:
			var x0: float = NAV_X[ix]
			var z0: float = NAV_Z[iz]
			if x0 == -45.0 and z0 == -45.0:
				continue
			# ground only: townsfolk walk the streets, not the roofs, sheds or galleries
			var aabb := AABB(Vector3(x0, -1.0, z0), Vector3(NAV_X[ix + 1] - x0, 2.0, NAV_Z[iz + 1] - z0))
			var nm := NavigationMesh.new()
			nm.geometry_parsed_geometry_type = NavigationMesh.PARSED_GEOMETRY_STATIC_COLLIDERS
			nm.agent_radius = 0.5
			nm.agent_height = 1.75
			nm.agent_max_climb = 0.25
			nm.agent_max_slope = 30.0
			nm.cell_size = 0.25          # 4.0 / 0.25 is an exact 16 voxels: no "border_size is ceiled" warning
			nm.cell_height = 0.25
			nm.edge_max_error = 1.0
			nm.filter_baking_aabb = aabb.grow(4.0)
			nm.border_size = 4.0
			_nav_pending += 1
			NavigationServer3D.bake_from_source_geometry_data_async(nm, src, _on_chunk.bind(nm))


func _on_chunk(nm: NavigationMesh) -> void:
	var r := NavigationRegion3D.new()
	r.name = "NavChunk%d" % _nav_regions.size()
	r.navigation_mesh = nm
	add_child(r)
	_nav_regions.append(r)
	_nav_pending -= 1
	if _nav_pending == 0:
		print("[smoke] city nav chunks baked in %d ms" % (Time.get_ticks_msec() - _tb))
		_report.call_deferred()


## Smoke line: chunk count, polygons, which district targets the townsfolk can reach from the square, triangles.
func _report() -> void:
	var district := get_parent()
	for i in 600:
		if district == null or not district.has_method("nav_ready") or district.nav_ready():
			break
		await get_tree().physics_frame
	# the chunk regions join the map on its next sync: wait for the iteration to move on twice
	if not is_inside_tree():
		return
	var it0 := NavigationServer3D.map_get_iteration_id(get_world_3d().navigation_map)
	for i in 300:
		await get_tree().physics_frame
		if not is_inside_tree():
			return
		if NavigationServer3D.map_get_iteration_id(get_world_3d().navigation_map) > it0 + 1:
			break
	var polys := 0
	for r in _nav_regions:
		polys += (r as NavigationRegion3D).navigation_mesh.get_polygon_count()
	var map := get_world_3d().navigation_map
	var from := Vector3(0, 0, -20)
	var bad := PackedStringArray()
	var ok := 0
	for c in data.get("checks", []):
		var to := Vector3(float(c[1]), 0.0, float(c[2]))
		var path := NavigationServer3D.map_get_path(map, from, to, true)
		var end: Vector3 = path[-1] if path.size() > 0 else from
		if Vector2(end.x - to.x, end.z - to.z).length() > 2.5:
			bad.append("%s(%.0f)" % [c[0], Vector2(end.x - to.x, end.z - to.z).length()])
		else:
			ok += 1
	print("[smoke] city chunks=%d polys=%d reachable=%d/%d unreachable=%s placed=%d static_tris=%d" % [_nav_regions.size(), polys,
			ok, (data.get("checks", []) as Array).size(), bad, (data.get("place", []) as Array).size(), _count_tris(get_parent())])
	print("[smoke] city outer_tris=%d" % _count_tris(self))


func _count_tris(root: Node) -> int:
	var total := 0
	var per_mesh := {}
	for n in root.find_children("*", "", true, false):
		var mesh: Mesh = null
		var mult := 1
		if n is MeshInstance3D:
			var mi := n as MeshInstance3D
			if mi.skin != null or mi.get_parent() is Skeleton3D or mi.global_position.y < -30.0:
				continue                      # figures and the interior sets under the map are not the townscape
			mesh = mi.mesh
		elif n is MultiMeshInstance3D and (n as MultiMeshInstance3D).multimesh:
			mesh = (n as MultiMeshInstance3D).multimesh.mesh
			mult = (n as MultiMeshInstance3D).multimesh.instance_count
		if mesh == null or not (mesh is ArrayMesh):
			continue
		if not per_mesh.has(mesh):
			var t := 0
			for s in mesh.get_surface_count():
				var il := (mesh as ArrayMesh).surface_get_array_index_len(s)
				t += (il if il > 0 else (mesh as ArrayMesh).surface_get_array_len(s)) / 3
			per_mesh[mesh] = t
		total += int(per_mesh[mesh]) * mult
	return total


# ------------------------------------------------------------------ inspection shots (`-- --outer-shot=/dir`)
func _shot_dir() -> String:
	for a in OS.get_cmdline_user_args():
		if a.begins_with("--outer-shot="):
			return a.trim_prefix("--outer-shot=")
	return ""


func _shots(dir: String) -> void:
	print("[smoke] outer shots: waiting for the town to build")
	await get_tree().create_timer(1.0).timeout
	while is_inside_tree() and not built:
		await get_tree().process_frame
	print("[smoke] outer shots: town built, capturing to ", dir)
	for i in 30:
		await get_tree().process_frame
	if not is_inside_tree():
		return
	for c in get_tree().root.find_children("*", "CanvasLayer", true, false):
		(c as CanvasLayer).visible = false
	var cam := Camera3D.new()
	cam.fov = 60
	cam.far = 900
	add_child(cam)
	var sun := DirectionalLight3D.new()
	sun.rotation_degrees = Vector3(-40, 35, 0)
	sun.light_energy = 1.6
	sun.visible = false
	add_child(sun)
	var shots: Array = []
	for s in data.get("shots", []):
		shots.append([s[0], Vector3(s[1][0], s[1][1], s[1][2]), Vector3(s[2][0], s[2][1], s[2][2])])
	shots += [
		["fountain", Vector3(9, 2.6, -11), Vector3(4.5, 1.5, -16.3)],
		["clock_tower", Vector3(-12, 18, 30), Vector3(-16, 20.5, 16)],
		["stained_glass", Vector3(34, 9, -66), Vector3(34, 10, -51)],
		["roof_snow", Vector3(-15, 21, -21), Vector3(-19, 14, -31)],
		["balcony", Vector3(3, 11.8, -22.5), Vector3(0, 11.3, -27.4)],
		["shutters", Vector3(-16.5, 5.6, -23.2), Vector3(-19.5, 5.2, -27.6)],
		["pillory", Vector3(-22.5, 2.2, 22.5), Vector3(-26, 1.5, 19.5)],
		["gutter", Vector3(-46, 2.0, 20), Vector3(-42, 0.0, 34)],
		["forge", Vector3(-128, 2.4, 1), Vector3(-128, 1.2, 9.5)],
		["windmill", Vector3(-40, 6, -170), Vector3(-60, 8, -186)],
		["watermill", Vector3(-140, 4, 20), Vector3(-150, 2.5, 34)],
		["synagogue", Vector3(60, 5, 168), Vector3(60, 6, 180)],
		["uniate_church", Vector3(64, 5, 170), Vector3(64, 9, 158)],
		["campanile", Vector3(8, 8, -44), Vector3(18, 18, -50)],
		["wawel_skyline", Vector3(-12, 12, 112), Vector3(-60, 30, 225)],
	]
	for s in shots:
		cam.look_at_from_position(s[1], s[2])
		for lit in [false, true]:
			sun.visible = lit
			for f in 4:
				cam.current = true
				await get_tree().process_frame
			if not is_inside_tree():
				return
			var err := get_viewport().get_texture().get_image().save_png("%s/outer_%s%s.png" % [dir, s[0], "_lit" if lit else ""])
			if err != OK:
				print("[smoke] outer shot %s failed: %d" % [s[0], err])
	print("[smoke] outer shots: %d views saved" % shots.size())
	sun.queue_free()
	cam.queue_free()
	for c in get_tree().root.find_children("*", "CanvasLayer", true, false):
		(c as CanvasLayer).visible = true
	print("[smoke] outer city shots in ", dir)
